package selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class WebServerExternalLinkTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public void webServerExternalLinkTest() {
        driver.get("http://localhost:8080/a.html");
        driver.findElement(By.linkText("do external links work?")).click();
        driver.findElement(By.name("q")).sendKeys("cat");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".g:nth-child(1) > div:nth-child(2) > .tF2Cxc .LC20lb")).click();
        {
            WebElement element = driver.findElement(By.linkText("growling"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
    }
}
